server {
    listen 80;

    location /producer {
        proxy_pass http://streams-producer:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /consumer {
        proxy_pass http://streams-consumer:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
